### ISSUE TITLE
Sprite corrupted when failing to save due to lack of free space

### ISSUE THREAD

**Issue by Urahara666** [LagoLunatic/DSVEdit#19] opened 2020-01-21 00:44 UTC
I just tried to change the color and disappeared no longer works in the game '-'
the sprite is missing

https://i.imgur.com/1QObnBR.png
https://i.imgur.com/DnBdoPC.png

**Comment by LagoLunatic** [comment] 2020-01-21 00:52
Please provide *exact* steps to reproduce the problem.
I tried changing the palette on the flying armor skill sprite and making other edits to it and nothing broke. You must have done something you're not mentioning.

**Comment by Urahara666** [comment] 2020-01-21 00:53
all i did was change the monster for this one and then tried to change the color of the flying armor

https://i.imgur.com/7kyCFWw.png

**Comment by LagoLunatic** [comment] 2020-01-21 00:56
Can't reproduce based on the information provided. Closing.

**Comment by Urahara666** [comment] 2020-01-21 00:57
but that was it, I just tried to change the color and it gave an error

**Comment by Urahara666** [comment] 2020-01-21 00:58
how do I put the sprite back? is giving this error
https://i.imgur.com/YTBJm8w.png

**Comment by LagoLunatic** [comment] 2020-01-21 00:58
Information on adding a free space overlay is included in the readme.

**Comment by Urahara666** [comment] 2020-01-21 00:59
need space just to change colors?

**Comment by LagoLunatic** [comment] 2020-01-21 01:01
>need space just to change colors?

Nope, I changed the colors for that sprite just fine without needing to do anything else.
![image](https://user-images.githubusercontent.com/19174152/72766810-7e2ea580-3bbf-11ea-9d8f-9d57776980d8.png)
Whatever you're describing with the word "colors" is not colors. You wouldn't get an error about free space if you only edited colors.

**Comment by Urahara666** [comment] 2020-01-21 01:02
that's exactly what happened, I just changed the colors and when I clicked on Apply the error '-'

**Comment by LagoLunatic** [comment] 2020-01-21 01:02
Record a video.

**Comment by Urahara666** [comment] 2020-01-21 01:02
ok

**Comment by Urahara666** [comment] 2020-01-21 01:10
https://www.youtube.com/watch?v=54THtImQIBc&

**Comment by LagoLunatic** [comment] 2020-01-21 01:14
I see, it does seem there's a bug when trying to save a sprite and there's no free space.

For changing colors though, it's not necessary to save the sprite at all. The GFX editor is separate from the sprite editor, so the color changes were already saved before you hit "Apply" in the sprite editor.

**Comment by Urahara666** [comment] 2020-01-21 01:15
but the sprite disappeared in the game '-'

**Comment by LagoLunatic** [comment] 2020-01-21 01:17
Indeed. That's the bug when trying to save a sprite and there's no free space I mentioned. I'll fix it for the next version, but for now you can avoid it by just not clicking "apply" in the first place.

**Comment by Urahara666** [comment] 2020-01-21 01:18
ok, but in the next version will I have to import the sprite back? because he disappeared and you can't go back

**Comment by LagoLunatic** [comment] 2020-01-21 01:20
It can't be recovered automatically, the bug erased the original sprite data.
Reload from a backup of your project.

**Comment by Urahara666** [comment] 2020-01-21 01:21
I have the backup but I can't import the return because it gives a space error, maybe in the next version I can

**Comment by LagoLunatic** [comment] 2020-01-21 01:23
>I have the backup but I can't import the return because it gives a space error, maybe in the next version I can

Nope. The free space error isn't a bug, it's just telling you you have no free space, so it's impossible for that to work.
Add free space and it should work in the current version.

**Comment by Urahara666** [comment] 2020-01-21 01:24
I saw the README file but I didn't understand almost anything, if I delete things in the game like candles and some enemies I will get the free space

**Comment by LagoLunatic** [comment] 2020-01-21 01:26
>if I delete things in the game like candles and some enemies I will get the free space

Technically yes, but it will be free space in the wrong overlay, so that won't help you.

**Comment by Urahara666** [comment] 2020-01-21 01:30
so I'll leave it the way it is and not change the colors anymore, thanks for the suport

**Comment by LagoLunatic** [comment] 2020-01-21 01:31
>and not change the colors anymore

Colors have nothing to do with this though... you can edit colors without running into the bug at all.

**Comment by Urahara666** [comment] 2020-01-21 01:32
allright, thanks

**Closed** 2020-01-21 02:38 UTC
