### ISSUE TITLE
DSVEdit refuses to launch; claims missing procedures/libraries that *ARE* present

### ISSUE THREAD

**Issue by DarkPulse** [LagoLunatic/DSVEdit#3] opened 2017-05-07 19:33 UTC
I've been trying to get DSVEdit to launch on my PC, and it flat-out, absolutely refuses to.

I thought it was path length errors (since this project has folders for days) but it seems to not be that.

The Visual C++ Redistributables are, as far as I know, installed (it's showing up in my Programs list, anyway). Any idea why it's just plain puking? I've shortened the paths, I've tried running as admin, I even tried moving it to a different drive... nothing.

![image](https://cloud.githubusercontent.com/assets/5454684/25784399/1e4d0944-333a-11e7-9c46-53f1b12bab44.png)

All the files are there, so I really don't see what gives.

**Comment by LagoLunatic** [comment] 2017-05-07 20:05
What operating system are you on? And 32 bit or 64 bit?

**Comment by DarkPulse** [comment] 2017-05-07 20:07
Win7, 64-bit.

**Comment by LagoLunatic** [comment] 2017-05-07 20:47
Well, I tried it on a win7 64 bit machine, worked fine.
I read that that error could be caused by something or another being missing from your path, so I deleted everything from my path but it still ran fine.

I really don't like when ruby gives these nonsense errors, there's like no way to figure out what they mean.

Only thing I can suggest is to try running it directly from source and seeing if that works.
If you try to run it from source you need to install Ruby 2.0.0 or higher 32 bit version, and Qt 4.8.6 exactly.

**Comment by DarkPulse** [comment] 2017-05-07 21:02
Could it be because I've got other versions of Ruby installed, then?

I've got 2.2.3-p173 installed for another program that I ran.

**Comment by LagoLunatic** [comment] 2017-05-07 21:27
Hmm, that shouldn't affect it since the executable should be running the ruby that comes with the dsvedit download. And 2.2.3 should be able to run qtbindings anyway, I believe. The exact version I use is 2.2.4p230.

But it might be possible it's causing some kind of conflict anyway, I'm not sure. Might be worth uninstalling any other versions of Ruby and Qt you have to see if it changes anything.

**Comment by DarkPulse** [comment] 2017-05-19 03:01
I realized something that may be causing this. Long shot, but it might be worth considering.

My user directory (and Windows username) happens to have a space in its name. Is DSVEdit friendly towards that?

If not, it could be choking due to that.

**Comment by LagoLunatic** [comment] 2017-05-19 03:12
DSVEdit works fine if the path has a space in the name. It doesn't work if you have any kind of unicode characters in the path though.
But the path in your screenshot doesn't look like it's got any spaces or unicode characters.

You're not trying to run DSVEdit 1.0 right? That version didn't work on lots of people's computers due to missing files, but that was fixed in all later builds.

If you haven't already tried running it from source, I recommend that. The executable build is held together by duct tape and is probably the cause of whatever issue you're having.

**Comment by DarkPulse** [comment] 2017-05-20 17:36
I downloaded 1.5.0.

As for the EXE version basically being worthless, bummer. I am trying to run it from the EXE, so I'll have to run the from-source version instead, so I guess I'll go hunt for QT 4.8.6.

**Comment by LagoLunatic** [comment] 2017-05-20 17:44
The exe version isn't worthless for everyone, you're the first person I've heard of that couldn't launch it. Because of that, I'm not actually sure the source version will run any better for you either. I have no clue what the problem you're running into is. I'm just guessing that it's maybe related to the exe version?

Qt 4.8.6 is here: https://download.qt.io/archive/qt/4.8/4.8.6/

**Comment by DarkPulse** [comment] 2017-05-20 17:55
Got that downloaded and installed (The VS2010 edition - not sure if that matters), tried to run it via dsvedit.rb.

Unfortunately, that seems to not be doing any better.

![image](https://cloud.githubusercontent.com/assets/5454684/26278250/b3011868-3d63-11e7-9b8c-d99ecde12af3.png)

**Comment by LagoLunatic** [comment] 2017-05-20 18:03
It looks like you didn't install the Qt gem. Run `bundle install` and it will install all the necessary gems for dsvedit. If you don't already have bundler then first run `gem install bundler`, *then* run `bundle install`.

**Comment by LagoLunatic** [comment] 2017-05-20 18:09
Also, I just noticed your screenshot says "Ruby22-x64". When I first started making dsvedit over a year ago I initially tried the 64 bit version of ruby too, and learned the hard way after many many errors that it's experimental and doesn't work at all.

It's possible that the situation has changed since then, but I would err on the side of caution and use the 32 bit version of ruby.

**Comment by DarkPulse** [comment] 2017-05-20 18:42
Deleted the x64 install, downloaded and installed x86 Ruby 2.3.3-p222. Did `gem install bundler`, then ran `bundle install`, and wound up getting this.

![image](https://cloud.githubusercontent.com/assets/5454684/26278526/6f754310-3d6a-11e7-96e5-dbb839b0a09e.png)

![image](https://cloud.githubusercontent.com/assets/5454684/26278528/7489e3ce-3d6a-11e7-9f98-412c790ed297.png)

(Your patience is awesome, by the way. Respect.)

**Comment by LagoLunatic** [comment] 2017-05-20 19:03
Ah, I forgot oily_png needs the devkit. Alright, here's how to install it:
* Download the [32 bit devkit](https://dl.bintray.com/oneclick/rubyinstaller/DevKit-mingw64-32-4.7.2-20130224-1151-sfx.exe)
* Extract it to `C:\Ruby22\DevKit`
* Go to `C:\Ruby22\DevKit` in a cmd prompt, and then run `ruby dk.rb init` followed by `ruby dk.rb install`

Then you should be able to install oily_png. You *might* need to restart after installing the devkit, but I don't think so.

**Comment by DarkPulse** [comment] 2017-05-20 19:46
oily_png now works, but I ended up shooting myself in the foot by installing Ruby 2.3.3, as apparently nokogiri (or at least, the version of it you're using?) needs a Ruby less than 2.3. You may want to mention in your main post's readme that you will not want a Ruby higher than 2.2, but right now it says "Ruby 2.0.0 or higher." ([The last RubyInstaller version before then off RubyInstaller's site is 2.2.6-p396.](https://rubyinstaller.org/downloads/))

So I swapped that out, re-installed bundler and the Devkit, and it installed all the gems. And, well...

![image](https://cloud.githubusercontent.com/assets/5454684/26278892/121e2732-3d73-11e7-855e-97bff05dd962.png)

...we're right back to where we started. :sob:

**Comment by LagoLunatic** [comment] 2017-05-20 19:54
If the only problem is that I'm using an old nokogiri, how about if you run `bundle update nokogiri`?

I'm just lazy and haven't updated any gems since I started working on dsvedit, but soon I'll get around to updating them all assuming it doesn't break anything.

**Comment by LagoLunatic** [comment] 2017-05-20 20:00
Oh wait I just noticed the part where you said you tried ruby 2.2 and it gave you the same error as the executable...

Well, in that case I guess the executable isn't at fault. I really don't know why you're getting that "the specified procedure could not be found" thing. I'll try to mess with some stuff randomly again and see if I can reproduce it.

**Comment by LagoLunatic** [comment] 2017-05-20 21:03
Does this build run at all for you?
https://www.dropbox.com/s/zu7lg0fuqwvm7xw/DSVania_Editor_1.5.0_EXPERIMENTAL.zip?dl=0

I still can't reproduce the error you're getting, so I just tried updating all the gems, and switched to ruby 2.3 64 bit version. (Apparently the 64 bit version not working was just in ruby 2.2.)

**Comment by DarkPulse** [comment] 2017-05-20 21:16
Negative. Still giving the exact same behavior. I copied all the files over the previous 1.5.0 source version.

![image](https://cloud.githubusercontent.com/assets/5454684/26279366/dee33ef4-3d7f-11e7-8297-eaca4cec93b1.png)

**Comment by DarkPulse** [comment] 2017-05-20 21:17
Yes, that one launched right up for me, surprisingly enough. I'm not sure what you did, but it seems to have worked when launching it from EXE.

**Comment by LagoLunatic** [comment] 2017-05-20 21:41
Huh, that's unexpected. Looks like guessing at random can yield results after all.

One last test: Can you check if this build runs or not?
https://www.dropbox.com/s/yf1q179jylzbo1m/DSVania_Editor_1.5.0_EXPERIMENTAL_win32.zip?dl=0

It's got the updated stuff from the last one, but it's using 32 bit ruby instead of 64 bit. I suspect the problem was that your computer needs the 64 bit version, and this build won't work. But I want to be sure, because I don't want to go through the extra work of uploading two versions of future dsvedit releases if it's actually something unrelated.

**Comment by DarkPulse** [comment] 2017-05-20 22:07
You seem to be right on the money. It failed.

![image](https://cloud.githubusercontent.com/assets/5454684/26279635/27aec3c2-3d87-11e7-9712-40ffb9f2ee0c.png)

**Closed** 2017-08-09 14:17 UTC
