### ISSUE TITLE
HoD: Layer resizing of initial room corrupts built ROM and forces editor crash on startup

### ISSUE THREAD

**Issue by 4lorn5** [LagoLunatic/DSVEdit#60] opened 2021-12-03 20:24 UTC
When resizing the initial room's layer size and committing the change, DSVania will keep working as if nothing is wrong, allowing a user to save and build a ROM. However, when opening the editor again, a warning pop-up will suggest otherwise:

Error: BGLayer::LayerReadError: Invalid Layer Size: 16x68

The error is reported and the program will terminate by itself. This change is facilitated by, and made directly through DSVania, yet only produces an error upon exiting and reopening the editor, potentially causing hours of work to be lost as no warning is given otherwise. No external editor or ROM hacking was used to modify the room's size; it was done purely through the editor, reducing layer size to sizes between 2 and 5.

Screenshot:

https://i.ibb.co/vB0KfnJ/Untitled.jpg

**Comment by LagoLunatic** [comment] 2021-12-03 21:50
I'm not able to reproduce this. I opened a vanilla HoD ROM, changed the first room's first layer's size to 5x1 instead of 6x1, saved and reopened DSVEdit, and it worked as expected with no crash. I went on to make several other changes to the sizes of various layers in the first room in DSVEdit and reloaded, and it worked as expected each time.

The crash you're getting must be caused by something else you changed besides layer size. This is supported by the fact that, even if you did tell DSVEdit to resize a room to 16x68 it would forcibly cap the size at 15x15 as that is the maximum allowed size.

The only ways I can think of that you could get the error in that screenshot are:
* You modified the layer's size to be 16x68 via some external program that is not DSVEdit (you say you didn't do this)
* DSVEdit was writing some unrelated data and overwrote the layer's size because that unrelated data and the layer both pointed to the same location (this could happen if you manually adjusted some pointers in DSVEdit without understanding what you were doing)

If you want me to see if I can check what the unrelated thing that you pointed at the layer on accident is, create an IPS patch of your hack and upload it somewhere so I can check your project.

**Comment by LagoLunatic** [comment] 2021-12-28 18:20
Closing since OP isn't providing any more info

**Closed by LagoLunatic** 2021-12-28 18:20 UTC
